### ISSUE TITLE
Unable to update filters

### ISSUE THREAD

**Issue by timster** [AdguardTeam/AdGuardForSafari#115]
I'm unable to update filters on my Mac. I suspect it's because I'm behind a corporate proxy.

Does AdGuard use the system proxy?

Is there  a log somewhere that would have more details so I could troubleshoot?

**Comment by ameshkov** [comment]
Yep, press `alt + command + i` to open dev tools

**Comment by ameshkov** [comment]
> I suspect this is because our proxy re-signs SSL certificates and these are not trusted by AdGuard.

Hm, in theory, AG should trust your certificate if it's added to the system keychain. Do you have it there?

**Comment by brian-eng** [comment]
> Hm, in theory, AG should trust your certificate if it's added to the system keychain. Do you have it there?

@ameshkov I have a similar problem as OP, but I definitely have the certificate added to the System Keychain. Since the issue is old I'm not sure what version this was reported for, but I'm using 1.5.4 right now.

I can download the filter list manually (https://filters.adtidy.org/extension/chromium/filters/2.txt for example) via Safari or Apple provided curl with no errors (both use the self-signed certificate).

Opening the Developer Tools via command + alt + i and looking at the console I don't see anything, but running it via the Terminal I get this message when trying to update the filters.

```
16:13:27.358 › Error retrieved response from server for filters [2,3,4,12], cause: Error: self signed certificate in certificate chain
Stack trace:
Error: self signed certificate in certificate chain
    at TLSSocket.onConnectSecure (_tls_wrap.js:1257:34)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12)
```

Also the field for the last update in the App when I try to refresh the lists gets updated despite it actually failing to get any of the lists. If I close and re-open the App it is back to the old date prior to trying to update the filters.

Let me know if there's any other information I can provide or if there's something else I can do/test.

**Comment by SoLenny** [comment]
@timster @brian-eng Hello, guys. If it possible, please send us logs. To do this, click on "AdGuard for Safari" on tab bar then select "Export logs and system info.."

**Comment by zzebrum** [comment]
@timster @brian-eng any update on the issue?

**Comment by brian-eng** [comment]
@zzebrum Still not working for me on version 1.6.4 as I'm guessing MAS will get 1.7.0 eventually.

@SoLenny I've put the contents of the exported logs at least temporarily in this [gist](https://gist.github.com/brian-eng/ec5dfaad17dbb7b33c673044723d368e)

**Comment by SoLenny** [comment]
@brian-eng Hello, please try updating the application manually via MAS.

**Comment by timster** [comment]
I don't have the problem anymore. Corporate changed the way our proxy works so that may have contributed to the solution.

**Comment by brian-eng** [comment]
> @brian-eng Hello, please try updating the application manually via MAS.

@SoLenny Done, however 1.7.1 has same symptoms as earlier versions. Namely trying to manually update the filters will update the time, but get a "Filters' update error" notification and not actually update anything. Haven't had AdGuard running long enough to have the automatic updates kick in, but I have no doubt they'd fail as well.

Made a new [gist](https://gist.github.com/brian-eng/d224bd5fef885ec06a574064dded0609) with log information (which looks pretty similar to all the earlier ones) after updating to the latest version.

**Comment by ameshkov** [comment]
Sorry that it took us so long to categorize it as a bug, assigned to v1.8

**Comment by Rinfore** [comment]
I have exactly the same issue here "trying to manually update the filters will update the time, but get a "Filters' update error" notification and not actually update anything." with v1.11.16.

I assume this issue has not been resolved? Is there any workaround?

**Comment by Rinfore** [comment]
Hi @alexx7311, could I enquire whether there are any updates on this issue? It appears to still be present on Version 1.11.17
