### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by ameshkov** [AdguardTeam/AdGuardForSafari#180]
@jocamero commented on [Thu Jun 06 2019](https://github.com/AdguardTeam/AdguardForMac/issues/524)

### Steps to reproduce
1.  Open program after a new install.

### Expected behavior
not crash

### Actual behavior
crash

<details><summary>Screenshot:</summary>

Error:

Uncaught Exception:
Error: dlopen(/var/folders/1h/t6jyx1vx3558l2dp0rw5yvbm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.lKw7sE, 1): no suitable image found.  Did find:
	/var/folders/1h/t6jyx1vx3558l2dp0rw5yvbm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.lKw7sE: code signature in (/var/folders/1h/t6jyx1vx3558l2dp0rw5yvbm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.lKw7sE) not valid for use in process using Library Validation: Library load disallowed by System Policy
	/var/folders/1h/t6jyx1vx3558l2dp0rw5yvbm0000gn/T/com.adguard.safari.AdGuard/.TC3Q7MAJXF.com.adguard.safari.AdGuard.lKw7sE: stat() failed with errno=17
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/node_modules/bindings/bindings.js:81:44)
    at Object.<anonymous> (/Applications/AdGuard for Safari.app/Contents/Resources/app.asar/node_modules/safari-ext/index.js:1:189)

</details>

### Customer ID 
app won't open, so not possible

### Your environment
MacOS 10.15 Beta (19A471t)
Safari Version 13.0 (15608.1.24.40.4)

Tried to install from the App Store and from the Adguard website.

**Comment by ameshkov** [comment]
@jocamero try installing the beta version please: https://github.com/AdguardTeam/AdGuardForSafari/releases

**Comment by ameshkov** [comment]
Ah, wait, this is MacOS Catalina - there's a known bug about it: https://github.com/AdguardTeam/AdGuardForSafari/issues/172
